server:
  port: 8086

spring:
  application:
    name: codebase-cr
  
  # Spring AI 配置
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
  datasource:
    url: jdbc:sqlite:data/codebasewiki_db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: test
    password: test
    
    # 向量数据库配置 (Chroma)
#    vectorstore:
#      elasticsearch:
#        initialize-schema: true
#        index-name: yingzi_
#        similarity: cosine
#        dimensions: 1536

# 应用相关配置
app:
  github:
    token: ${GITHUB_TOKEN:your-github-token}
    webhook:
      secret: ${GITHUB_WEBHOOK_SECRET:your-webhook-secret}
  
  knowledge:
    # 知识库存储路径
    base-path: ${KNOWLEDGE_BASE_PATH:./knowledge-base}
    # 百炼知识库索引名称
    index-name: ${BAILIAN_INDEX_NAME:code-review-knowledge}
    style-guide:
      # 编码规范文档路径
      documents-path: ${app.knowledge.base-path}/style-guides
    project:
      # 项目代码缓存路径
      cache-path: ${app.knowledge.base-path}/projects

# 日志配置
logging:
  level:
    com.hxg.aicodereviewer: INFO
    org.springframework.ai: DEBUG
    org.kohsuke.github: WARN
    com.alibaba.cloud.ai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# 异步任务配置
task:
  execution:
    pool:
      core-size: 2
      max-size: 5
      queue-capacity: 100
      keep-alive: 60s

# Memory服务配置
memory:
  service:
    url: http://localhost:8080

# Feign配置
feign:
  client:
    config:
      memory-service:
        connectTimeout: 5000
        readTimeout: 10000
        loggerLevel: basic
  hystrix:
    enabled: false
  circuitbreaker:
    enabled: false

