server:
  port: 8086

spring:
  application:
    name: codebase-cr
  
  # Spring AI 配置
  ai:
    # 模型提供商选择: dashscope（阿里云，默认）| ollama（本地模型）| openai（OpenAI）
    provider: ${SPRING_AI_PROVIDER:dashscope}
    
    dashscope:
      api-key: ${DASHSCOPE_API_KEY:your-dashscope-api-key}
      chat:
        options:
          model: ${DASHSCOPE_CHAT_MODEL:qwen3-coder-plus}
      embedding:
        options:
          model: ${DASHSCOPE_EMBEDDING_MODEL:text-embedding-v4}
    
    # Ollama 配置（本地大模型）
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_CHAT_MODEL:qwen2.5-coder:14b}
          temperature: 0.7
      embedding:
        options:
          model: ${OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
    
    # OpenAI 配置
    openai:
      api-key: ${OPENAI_API_KEY:your-openai-api-key}
      base-url: ${OPENAI_BASE_URL:https://api.openai.com}
      chat:
        options:
          model: ${OPENAI_CHAT_MODEL:gpt-4o}
          temperature: 0.7
      embedding:
        options:
          model: ${OPENAI_EMBEDDING_MODEL:text-embedding-3-small}
  datasource:
    url: jdbc:sqlite:data/codebasewiki_db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: test
    password: test

# 应用相关配置
app:
  github:
    token: ${GITHUB_TOKEN:your-github-token}
    webhook:
      secret: ${GITHUB_WEBHOOK_SECRET:your-webhook-secret}
  
  knowledge:
    # 知识库存储路径
    base-path: ./knowledge-base
    # 百炼知识库索引名称
    index-name: code-review-knowledge
    style-guide:
      # 编码规范文档路径
      documents-path: /style-guides
    project:
      # 项目代码缓存路径
      cache-path: /projects

# 异步任务配置
task:
  execution:
    pool:
      core-size: 2
      max-size: 5
      queue-capacity: 100
      keep-alive: 60s

# 通知配置
notification:
  # 是否启用通知功能
  enabled: true
  # 启用的通知渠道
  channels:
    - feishu
    - dingtalk
  
  # 飞书配置
  feishu:
    enabled: ${FEISHU_ENABLED:true}
    # Wiki文档机器人
    wiki-webhook: ${FEISHU_WIKI_WEBHOOK:your-feishu-wiki-webhook}
    wiki-secret: ${FEISHU_WIKI_SECRET:your-feishu-wiki-secret}
    # 代码评审机器人
    review-webhook: ${FEISHU_REVIEW_WEBHOOK:your-feishu-review-webhook}
    review-secret: ${FEISHU_REVIEW_SECRET:your-feishu-review-secret}
  
  # 钉钉配置
  dingtalk:
    enabled: ${DINGTALK_ENABLED:true}
    # Wiki文档机器人
    wiki-webhook: ${DINGTALK_WIKI_WEBHOOK:your-dingtalk-wiki-webhook}
    wiki-secret: ${DINGTALK_WIKI_SECRET:your-dingtalk-wiki-secret}
    # 代码评审机器人
    review-webhook: ${DINGTALK_REVIEW_WEBHOOK:your-dingtalk-review-webhook}
    review-secret: ${DINGTALK_REVIEW_SECRET:your-dingtalk-review-secret}

# 日志输出配置
logging:
  level:
    root: INFO
    # Tool调用监控日志
    com.way.monitor: INFO
    com.way.llm.tool: DEBUG
    com.way.llm.service: INFO
  org:
    springframework:
      boot: error
  file:
    name: ./logs/codebasereview.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"




