server:
  port: 8085
  tomcat:
    uri-encoding: UTF-8

spring:
  # Spring AI 配置
  ai:
    dashscope:
      api-key: ${DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-plus-2025-01-25
  application:
    name: CodeBase-Wiki
  datasource:
    url: jdbc:sqlite:data/codebasewiki_db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: test
    password: test
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
      continue-on-error: true

# 日志输出配置
logging:
  level:
    root: INFO
  org:
    springframework:
      boot: error
  file:
    name: ./logs/codebasewiki.log