server:
  port: 8080

spring:
  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: memory-index-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.hxg.memory.queue.model,com.hxg.queue.model"
        spring.json.value.default.type: com.hxg.memory.queue.model.MemoryIndexTask
        spring.json.use.type.headers: false
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  datasource:
    url: jdbc:sqlite:data/codebasewiki_db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: test
    password: test
mem0:
  client:
    base-url: http://127.0.0.1:8888
    max-retry-attempts: 1
  server:
    version: v1.1
    vector-store:
      provider: pgvector
      config:
        host: ${POSTGRES_HOST:postgres}
        port: ${POSTGRES_PORT:5432}
        dbname: ${POSTGRES_DB:postgres}
        user: ${POSTGRES_USER:postgres}
        password: ${POSTGRES_PASSWORD:postgres}
        collection-name: ${POSTGRES_COLLECTION_NAME:memories}
    graph-store:
      provider: neo4j
      config:
        url: ${NEO4J_URI:bolt://neo4j:7687}
        username: ${NEO4J_USERNAME:neo4j}
        password: ${NEO4J_PASSWORD:mem0graph}
    llm:
      provider: openai
      config:
        api-key: ${AI_DASHSCOPE_API_KEY}
        temperature: 0.2
        model: qwen-turbo
        openai-base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
    embedder:
      provider: openai
      config:
        api-key: ${AI_DASHSCOPE_API_KEY}
        model: text-embedding-v4
        openai-base-url: https://dashscope.aliyuncs.com/compatible-mode/v1

project:
  memory:
    kafka:
      topics:
        mem-index: "memory-index-topic"
        mem-retry: "memory-index-retry-topic"
        mem-dlq: "memory-index-dlq"
      consumer:
        max-concurrency: 2
        process-interval: 1000
        max-retry: 3