server:
  port: 8086

spring:
  application:
    name: github-integration

# 应用相关配置
app:
  github:
    token: ${GITHUB_TOKEN}
    webhook:
      secret: ${GITHUB_WEBHOOK_SECRET}

# 日志配置
logging:
  level:
    com.hxg.aicodereviewer: INFO
    org.springframework.ai: DEBUG
    org.kohsuke.github: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"